---
title: "R Notebook"
output: html_notebook
---


```{r}

library(readr)
library(dplyr)
library(sampling)
library(samplingVarEst)

elecciones<- read_csv("~/Documents/MaestriaCD/Trabajo_Muestreo/Trabajo_final/007_ResElect_NACIONAL_seccs_PRES2012.csv")

## Lo primero que hay que hacer es sumar los partidos por coalicion

elecciones<-elecciones %>% mutate(EPN=PRI+PVEM+`COALICION PRI PVEM`) %>%
  mutate(AMLO=PRD + PT + `MOVIMIENTO CIUDADANO` + `COALICION PRD PT MC` +  `COALICION PRD PT` +
           `COALICION PRD MC`+`COALICION PT MC`) %>%
  mutate(JVM=PAN) %>%
  mutate(GC= `NUEVA ALIANZA`) %>%
  mutate(NoReg= `NO REGISTRADOS`) %>%
  mutate(Nulos=NULOS)  %>%
  select(-(8:21))
elecciones[is.na(elecciones)] <- 0

#Una vez que hicimos esto procedemos al responder las preguntas

## Numero de secciones por muestra
n1 <- 6500
n2 <- 500
n3 <- 250
n4 <- 100
n5 <- 50

## El N poblacional es

N<-nrow(elecciones)

## Extraer muestra n bajo muestreo aleatorio simple

set.seed(17)

muestra_1<-srswor1(n1,N)
muestra_2<-srswor1(n2,N)
muestra_3<-srswor1(n3,N)
muestra_4<-srswor1(n4,N)
muestra_5<-srswor1(n5,N)

## Entonces aplicamos estas muestas que obtuvimos a nuestros variables de interes
epn_1<-elecciones$EPN[muestra_1==1]
amlo_1<-elecciones$AMLO[muestra_1==1]
jvm_1<-elecciones$JVM[muestra_1==1]
gc_1<-elecciones$GC[muestra_1==1]
noreg_1<-elecciones$NoReg[muestra_1==1]
nulos_1<-elecciones$Nulos[muestra_1==1]

epn_2<-elecciones$EPN[muestra_2==1]
amlo_2<-elecciones$AMLO[muestra_2==1]
jvm_2<-elecciones$JVM[muestra_2==1]
gc_2<-elecciones$GC[muestra_2==1]
noreg_2<-elecciones$NoReg[muestra_2==1]
nulos_2<-elecciones$Nulos[muestra_2==1]

epn_3<-elecciones$EPN[muestra_3==1]
amlo_3<-elecciones$AMLO[muestra_3==1]
jvm_3<-elecciones$JVM[muestra_3==1]
gc_3<-elecciones$GC[muestra_3==1]
noreg_3<-elecciones$NoReg[muestra_3==1]
nulos_3<-elecciones$Nulos[muestra_3==1]

epn_4<-elecciones$EPN[muestra_4==1]
amlo_4<-elecciones$AMLO[muestra_4==1]
jvm_4<-elecciones$JVM[muestra_4==1]
gc_4<-elecciones$GC[muestra_4==1]
noreg_4<-elecciones$NoReg[muestra_4==1]
nulos_4<-elecciones$Nulos[muestra_4==1]

epn_5<-elecciones$EPN[muestra_5==1]
amlo_5<-elecciones$AMLO[muestra_5==1]
jvm_5<-elecciones$JVM[muestra_5==1]
gc_5<-elecciones$GC[muestra_5==1]
noreg_5<-elecciones$NoReg[muestra_5==1]
nulos_5<-elecciones$Nulos[muestra_5==1]

##Estimar el total de votos por cada uno de los candidatos de 2012 (EPN, AMLO, JVM, GQT, NoReg, y Nulos -
#notar que hay coaliciones, tendrá que crear nuevas columnas en los datos – creará un total de 6 columnas, que son las que utilizará -, para más información ver:


## Para usar el estimador de H-T primero tenemos que encontrar los Pk´s, estos son diferentes para cada muestra
pk_1<- rep(n1/N, times=n1)
pk_2<- rep(n2/N, times=n2)
pk_3<- rep(n3/N, times=n3)
pk_4<- rep(n4/N, times=n4)
pk_5<- rep(n5/N, times=n5)

v_epn_1<-Est.Total.NHT(epn_1, pk_1)
v_amlo_1<-Est.Total.NHT(amlo_1, pk_1)
v_jvm_1<-Est.Total.NHT(jvm_1, pk_1)
v_gc_1<-Est.Total.NHT(gc_1, pk_1)
v_noreg_1<-Est.Total.NHT(noreg_1, pk_1)
v_nulos_1<-Est.Total.NHT(nulos_1, pk_1)

v_epn_2<-Est.Total.NHT(epn_2, pk_2)
v_amlo_2<-Est.Total.NHT(amlo_2, pk_2)
v_jvm_2<-Est.Total.NHT(jvm_2, pk_2)
v_gc_2<-Est.Total.NHT(gc_2, pk_2)
v_noreg_2<-Est.Total.NHT(noreg_2, pk_2)
v_nulos_2<-Est.Total.NHT(nulos_2, pk_2)

v_epn_3<-Est.Total.NHT(epn_3, pk_3)
v_amlo_3<-Est.Total.NHT(amlo_3, pk_3)
v_jvm_3<-Est.Total.NHT(jvm_3, pk_3)
v_gc_3<-Est.Total.NHT(gc_3, pk_3)
v_noreg_3<-Est.Total.NHT(noreg_3, pk_3)
v_nulos_3<-Est.Total.NHT(nulos_3, pk_3)

v_epn_4<-Est.Total.NHT(epn_4, pk_4)
v_amlo_4<-Est.Total.NHT(amlo_4, pk_4)
v_jvm_4<-Est.Total.NHT(jvm_4, pk_4)
v_gc_4<-Est.Total.NHT(gc_4, pk_4)
v_noreg_4<-Est.Total.NHT(noreg_4, pk_4)
v_nulos_4<-Est.Total.NHT(nulos_4, pk_4)

v_epn_5<-Est.Total.NHT(epn_5, pk_5)
v_amlo_5<-Est.Total.NHT(amlo_5, pk_5)
v_jvm_5<-Est.Total.NHT(jvm_5, pk_5)
v_gc_5<-Est.Total.NHT(gc_5, pk_5)
v_noreg_5<-Est.Total.NHT(noreg_5, pk_5)
v_nulos_5<-Est.Total.NHT(nulos_5, pk_5)


MatPkl_1           <- Pkl.Hajek.s(pk_1)
var_epn_1<-VE.HT.Total.NHT(epn_1, pk_1, MatPkl_1)
var_amlo_1<-VE.HT.Total.NHT(amlo_1, pk_1, MatPkl_1)
var_jvm_1<-VE.HT.Total.NHT(jvm_1, pk_1, MatPkl_1)
var_gc_1<-VE.HT.Total.NHT(gc_1, pk_1, MatPkl_1)
var_noreg_1<-VE.HT.Total.NHT(noreg_1, pk_1, MatPkl_1)
var_nulos_1<-VE.HT.Total.NHT(nulos_1, pk_1, MatPkl_1)

MatPkl_2           <- Pkl.Hajek.s(pk_2)
var_epn_2<-VE.HT.Total.NHT(epn_2, pk_2, MatPkl_2)
var_amlo_2<-VE.HT.Total.NHT(amlo_2, pk_2, MatPkl_2)
var_jvm_2<-VE.HT.Total.NHT(jvm_2, pk_2, MatPkl_2)
var_gc_2<-VE.HT.Total.NHT(gc_2, pk_2, MatPkl_2)
var_noreg_2<-VE.HT.Total.NHT(noreg_2, pk_2, MatPkl_2)
var_nulos_2<-VE.HT.Total.NHT(nulos_2, pk_2, MatPkl_2)


MatPkl_3           <- Pkl.Hajek.s(pk_3)
var_epn_3<-VE.HT.Total.NHT(epn_3, pk_3, MatPkl_3)
var_amlo_3<-VE.HT.Total.NHT(amlo_3, pk_3, MatPkl_3)
var_jvm_3<-VE.HT.Total.NHT(jvm_3, pk_3, MatPkl_3)
var_gc_3<-VE.HT.Total.NHT(gc_3, pk_3, MatPkl_3)
var_noreg_3<-VE.HT.Total.NHT(noreg_3, pk_3, MatPkl_3)
var_nulos_3<-VE.HT.Total.NHT(nulos_3, pk_3, MatPkl_3)

MatPkl_4           <- Pkl.Hajek.s(pk_4)
var_epn_4<-VE.HT.Total.NHT(epn_4, pk_4, MatPkl_4)
var_amlo_4<-VE.HT.Total.NHT(amlo_4, pk_4, MatPkl_4)
var_jvm_4<-VE.HT.Total.NHT(jvm_4, pk_4, MatPkl_4)
var_gc_4<-VE.HT.Total.NHT(gc_4, pk_4, MatPkl_4)
var_noreg_4<-VE.HT.Total.NHT(noreg_4, pk_4, MatPkl_4)
var_nulos_4<-VE.HT.Total.NHT(nulos_4, pk_4, MatPkl_4)

MatPkl_5           <- Pkl.Hajek.s(pk_5)
var_epn_5<-VE.HT.Total.NHT(epn_5, pk_5, MatPkl_5)
var_amlo_5<-VE.HT.Total.NHT(amlo_5, pk_5, MatPkl_5)
var_jvm_5<-VE.HT.Total.NHT(jvm_5, pk_5, MatPkl_5)
var_gc_5<-VE.HT.Total.NHT(gc_5, pk_5, MatPkl_5)
var_noreg_5<-VE.HT.Total.NHT(noreg_5, pk_5, MatPkl_5)
var_nulos_5<-VE.HT.Total.NHT(nulos_5, pk_5, MatPkl_5)

std_epn_1   <- sqrt(var_epn_1)
std_amlo_1 <- sqrt(var_amlo_1)
std_jvm_1 <- sqrt(var_jvm_1)
std_gc_1 <- sqrt(var_gc_1)
std_noreg_1 <- sqrt(var_noreg_1)
std_nulos_1 <- sqrt(var_nulos_1)


std_epn_2   <- sqrt(var_epn_2)
std_amlo_2 <- sqrt(var_amlo_2)
std_jvm_2 <- sqrt(var_jvm_2)
std_gc_2 <- sqrt(var_gc_2)
std_noreg_2 <- sqrt(var_noreg_2)
std_nulos_2 <- sqrt(var_nulos_2)

std_epn_3   <- sqrt(var_epn_3)
std_amlo_3 <- sqrt(var_amlo_3)
std_jvm_3 <- sqrt(var_jvm_3)
std_gc_3 <- sqrt(var_gc_3)
std_noreg_3 <- sqrt(var_noreg_3)
std_nulos_3 <- sqrt(var_nulos_3)

std_epn_4   <- sqrt(var_epn_4)
std_amlo_4 <- sqrt(var_amlo_4)
std_jvm_4 <- sqrt(var_jvm_4)
std_gc_4 <- sqrt(var_gc_4)
std_noreg_4 <- sqrt(var_noreg_4)
std_nulos_4 <- sqrt(var_nulos_4)

std_epn_5   <- sqrt(var_epn_5)
std_amlo_5 <- sqrt(var_amlo_5)
std_jvm_5 <- sqrt(var_jvm_5)
std_gc_5 <- sqrt(var_gc_5)
std_noreg_5 <- sqrt(var_noreg_5)
std_nulos_5 <- sqrt(var_nulos_5)



# Y ahora calculemos nuestro error absoluto o precision al 95% de confianza
alpha              <- 0.05
abs_epn_1    <- std_epn_1*qnorm(1-alpha/2)
abs_amlo_1    <- std_amlo_1*qnorm(1-alpha/2)
abs_jvm_1    <- std_jvm_1*qnorm(1-alpha/2)
abs_gc_1    <- std_gc_1*qnorm(1-alpha/2)
abs_noreg_1    <- std_noreg_1*qnorm(1-alpha/2)
abs_nulos_1    <- std_nulos_1*qnorm(1-alpha/2)

abs_epn_2    <- std_epn_2*qnorm(1-alpha/2)
abs_amlo_2    <- std_amlo_2*qnorm(1-alpha/2)
abs_jvm_2    <- std_jvm_2*qnorm(1-alpha/2)
abs_gc_2    <- std_gc_2*qnorm(1-alpha/2)
abs_noreg_2    <- std_noreg_2*qnorm(1-alpha/2)
abs_nulos_2    <- std_nulos_2*qnorm(1-alpha/2)


abs_epn_3    <- std_epn_3*qnorm(1-alpha/2)
abs_amlo_3    <- std_amlo_3*qnorm(1-alpha/2)
abs_jvm_3    <- std_jvm_3*qnorm(1-alpha/2)
abs_gc_3    <- std_gc_3*qnorm(1-alpha/2)
abs_noreg_3    <- std_noreg_3*qnorm(1-alpha/2)
abs_nulos_3    <- std_nulos_3*qnorm(1-alpha/2)

abs_epn_4    <- std_epn_4*qnorm(1-alpha/2)
abs_amlo_4    <- std_amlo_4*qnorm(1-alpha/2)
abs_jvm_4    <- std_jvm_4*qnorm(1-alpha/2)
abs_gc_4    <- std_gc_4*qnorm(1-alpha/2)
abs_noreg_4    <- std_noreg_4*qnorm(1-alpha/2)
abs_nulos_4    <- std_nulos_4*qnorm(1-alpha/2)


abs_epn_5    <- std_epn_5*qnorm(1-alpha/2)
abs_amlo_5    <- std_amlo_5*qnorm(1-alpha/2)
abs_jvm_5    <- std_jvm_5*qnorm(1-alpha/2)
abs_gc_5    <- std_gc_5*qnorm(1-alpha/2)
abs_noreg_5    <- std_noreg_5*qnorm(1-alpha/2)
abs_nulos_5    <- std_nulos_5*qnorm(1-alpha/2)

# Entonces nuestros 4 intervalos de confianza a un nivel de 95% son:
liminf_epn_1  <- v_epn_1 - abs_epn_1
liminf_amlo_1  <- v_amlo_1 - abs_amlo_1
liminf_jvm_1  <- v_jvm_1 - abs_jvm_1
liminf_gc_1  <- v_gc_1 - abs_gc_1
liminf_noreg_1  <- v_noreg_1 - abs_noreg_1
liminf_nulos_1  <- v_nulos_1 - abs_nulos_1

limsup_epn_1  <- v_epn_1 + abs_epn_1
limsup_amlo_1  <- v_amlo_1 + abs_amlo_1
limsup_jvm_1  <- v_jvm_1 + abs_jvm_1
limsup_gc_1  <- v_gc_1 + abs_gc_1
limsup_noreg_1  <- v_noreg_1 + abs_noreg_1
limsup_nulos_1  <- v_nulos_1 + abs_nulos_1


liminf_epn_2  <- v_epn_2 - abs_epn_2
liminf_amlo_2  <- v_amlo_2 - abs_amlo_2
liminf_jvm_2  <- v_jvm_2 - abs_jvm_2
liminf_gc_2  <- v_gc_2 - abs_gc_2
liminf_noreg_2  <- v_noreg_2 - abs_noreg_2
liminf_nulos_2  <- v_nulos_2 - abs_nulos_2

limsup_epn_2  <- v_epn_2 + abs_epn_2
limsup_amlo_2  <- v_amlo_2 + abs_amlo_2
limsup_jvm_2  <- v_jvm_2 + abs_jvm_2
limsup_gc_2  <- v_gc_2 + abs_gc_2
limsup_noreg_2  <- v_noreg_2 + abs_noreg_2
limsup_nulos_2  <- v_nulos_2 + abs_nulos_2



liminf_epn_3  <- v_epn_3 - abs_epn_3
liminf_amlo_3  <- v_amlo_3 - abs_amlo_3
liminf_jvm_3  <- v_jvm_3 - abs_jvm_3
liminf_gc_3  <- v_gc_3 - abs_gc_3
liminf_noreg_3  <- v_noreg_3 - abs_noreg_3
liminf_nulos_3  <- v_nulos_3 - abs_nulos_3

limsup_epn_3  <- v_epn_3 + abs_epn_3
limsup_amlo_3  <- v_amlo_3 + abs_amlo_3
limsup_jvm_3  <- v_jvm_3 + abs_jvm_3
limsup_gc_3  <- v_gc_3 + abs_gc_3
limsup_noreg_3  <- v_noreg_3 + abs_noreg_3
limsup_nulos_3  <- v_nulos_3 + abs_nulos_3

liminf_epn_4  <- v_epn_4 - abs_epn_4
liminf_amlo_4  <- v_amlo_4 - abs_amlo_4
liminf_jvm_4  <- v_jvm_4 - abs_jvm_4
liminf_gc_4  <- v_gc_4 - abs_gc_4
liminf_noreg_4  <- v_noreg_4 - abs_noreg_4
liminf_nulos_4  <- v_nulos_4 - abs_nulos_4

limsup_epn_4  <- v_epn_4 + abs_epn_4
limsup_amlo_4  <- v_amlo_4 + abs_amlo_4
limsup_jvm_4  <- v_jvm_4 + abs_jvm_4
limsup_gc_4  <- v_gc_4 + abs_gc_4
limsup_noreg_4  <- v_noreg_4 + abs_noreg_4
limsup_nulos_4  <- v_nulos_4 + abs_nulos_4

liminf_epn_5  <- v_epn_5 - abs_epn_5
liminf_amlo_5  <- v_amlo_5 - abs_amlo_5
liminf_jvm_5  <- v_jvm_5 - abs_jvm_5
liminf_gc_5  <- v_gc_5 - abs_gc_5
liminf_noreg_5  <- v_noreg_5 - abs_noreg_5
liminf_nulos_5  <- v_nulos_5 - abs_nulos_5

limsup_epn_5  <- v_epn_5 + abs_epn_5
limsup_amlo_5  <- v_amlo_5 + abs_amlo_5
limsup_jvm_5  <- v_jvm_5 + abs_jvm_5
limsup_gc_5  <- v_gc_5 + abs_gc_5
limsup_noreg_5  <- v_noreg_5 + abs_noreg_5
limsup_nulos_5  <- v_nulos_5 + abs_nulos_5

# Ahora calculemos el coeficiente de variaci?n estimado de cada una de las 4 estimaciones...
cve_epn_1      <- std_epn_1/v_epn_1
cve_amlo_1      <- std_amlo_1/v_amlo_1
cve_jvm_1      <- std_jvm_1/v_jvm_1
cve_gc_1      <- std_gc_1/v_gc_1
cve_noreg_1      <- std_noreg_1/v_noreg_1
cve_nulos_1      <- std_nulos_1/v_nulos_1

cve_epn_2      <- std_epn_2/v_epn_2
cve_amlo_2      <- std_amlo_2/v_amlo_2
cve_jvm_2      <- std_jvm_2/v_jvm_2
cve_gc_2      <- std_gc_2/v_gc_2
cve_noreg_2      <- std_noreg_2/v_noreg_2
cve_nulos_2      <- std_nulos_2/v_nulos_2

cve_epn_3      <- std_epn_3/v_epn_3
cve_amlo_3      <- std_amlo_3/v_amlo_3
cve_jvm_3      <- std_jvm_3/v_jvm_3
cve_gc_3      <- std_gc_3/v_gc_3
cve_noreg_3      <- std_noreg_3/v_noreg_3
cve_nulos_3      <- std_nulos_3/v_nulos_3

cve_epn_4      <- std_epn_4/v_epn_4
cve_amlo_4      <- std_amlo_4/v_amlo_4
cve_jvm_4      <- std_jvm_4/v_jvm_4
cve_gc_4      <- std_gc_4/v_gc_4
cve_noreg_4      <- std_noreg_4/v_noreg_4
cve_nulos_4      <- std_nulos_4/v_nulos_4

cve_epn_5      <- std_epn_5/v_epn_5
cve_amlo_5      <- std_amlo_5/v_amlo_5
cve_jvm_5      <- std_jvm_5/v_jvm_5
cve_gc_5      <- std_gc_5/v_gc_5
cve_noreg_5      <- std_noreg_5/v_noreg_5
cve_nulos_5      <- std_nulos_5/v_nulos_5

```

Las salidas son:

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_epn<-c(v_epn_1,v_epn_2,v_epn_3,v_epn_4,v_epn_5,sum(elecciones$EPN))
var_epn<-c(var_epn_1,var_epn_2,var_epn_3,var_epn_4,var_epn_5,var(elecciones$EPN))
std_epn<-c(std_epn_1,std_epn_2,std_epn_3,std_epn_4,std_epn_5,sqrt(var(elecciones$EPN)))
abs_epn<-c(abs_epn_1,abs_epn_2,abs_epn_3,abs_epn_4,abs_epn_5,sqrt(var(elecciones$EPN))*qnorm(1-.05/2))
liminf_epn<-c(liminf_epn_1,liminf_epn_2,liminf_epn_3,liminf_epn_4,liminf_epn_5,0)
limsup_epn<-c(limsup_epn_1,limsup_epn_2,limsup_epn_3,limsup_epn_4,limsup_epn_5,0)
cve_epn<-c(cve_epn_1,cve_epn_2,cve_epn_3,cve_epn_4,cve_epn_5,0)

salida_epn<-cbind(output_1,est_epn,var_epn,std_epn,abs_epn,liminf_epn,limsup_epn,cve_epn)
colnames(salida_epn)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_epn

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_amlo<-c(v_amlo_1,v_amlo_2,v_amlo_3,v_amlo_4,v_amlo_5,sum(elecciones$AMLO))
var_amlo<-c(var_amlo_1,var_amlo_2,var_amlo_3,var_amlo_4,var_amlo_5,var(elecciones$AMLO))
std_amlo<-c(std_amlo_1,std_amlo_2,std_amlo_3,std_amlo_4,std_amlo_5,sqrt(var(elecciones$AMLO)))
abs_amlo<-c(abs_amlo_1,abs_amlo_2,abs_amlo_3,abs_amlo_4,abs_amlo_5,sqrt(var(elecciones$AMLO))*qnorm(1-.05/2))
liminf_amlo<-c(liminf_amlo_1,liminf_amlo_2,liminf_amlo_3,liminf_amlo_4,liminf_amlo_5,0)
limsup_amlo<-c(limsup_amlo_1,limsup_amlo_2,limsup_amlo_3,limsup_amlo_4,limsup_amlo_5,0)
cve_amlo<-c(cve_amlo_1,cve_amlo_2,cve_amlo_3,cve_amlo_4,cve_amlo_5,0)

salida_amlo<-cbind(output_1,est_amlo,var_amlo,std_amlo,abs_amlo,liminf_amlo,limsup_amlo,cve_amlo)
colnames(salida_amlo)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_amlo

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_jvm<-c(v_jvm_1,v_jvm_2,v_jvm_3,v_jvm_4,v_jvm_5,sum(elecciones$JVM))
var_jvm<-c(var_jvm_1,var_jvm_2,var_jvm_3,var_jvm_4,var_jvm_5,var(elecciones$JVM))
std_jvm<-c(std_jvm_1,std_jvm_2,std_jvm_3,std_jvm_4,std_jvm_5,sqrt(var(elecciones$JVM)))
abs_jvm<-c(abs_jvm_1,abs_jvm_2,abs_jvm_3,abs_jvm_4,abs_jvm_5,sqrt(var(elecciones$JVM))*qnorm(1-.05/2))
liminf_jvm<-c(liminf_jvm_1,liminf_jvm_2,liminf_jvm_3,liminf_jvm_4,liminf_jvm_5,0)
limsup_jvm<-c(limsup_jvm_1,limsup_jvm_2,limsup_jvm_3,limsup_jvm_4,limsup_jvm_5,0)
cve_jvm<-c(cve_jvm_1,cve_jvm_2,cve_jvm_3,cve_jvm_4,cve_jvm_5,0)

salida_jvm<-cbind(output_1,est_jvm,var_jvm,std_jvm,abs_jvm,liminf_jvm,limsup_jvm,cve_jvm)
colnames(salida_jvm)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_jvm

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_gc<-c(v_gc_1,v_gc_2,v_gc_3,v_gc_4,v_gc_5,sum(elecciones$GC))
var_gc<-c(var_gc_1,var_gc_2,var_gc_3,var_gc_4,var_gc_5,var(elecciones$GC))
std_gc<-c(std_gc_1,std_gc_2,std_gc_3,std_gc_4,std_gc_5,sqrt(var(elecciones$GC)))
abs_gc<-c(abs_gc_1,abs_gc_2,abs_gc_3,abs_gc_4,abs_gc_5,sqrt(var(elecciones$GC))*qnorm(1-.05/2))
liminf_gc<-c(liminf_gc_1,liminf_gc_2,liminf_gc_3,liminf_gc_4,liminf_gc_5,0)
limsup_gc<-c(limsup_gc_1,limsup_gc_2,limsup_gc_3,limsup_gc_4,limsup_gc_5,0)
cve_gc<-c(cve_gc_1,cve_gc_2,cve_gc_3,cve_gc_4,cve_gc_5,0)

salida_gc<-cbind(output_1,est_gc,var_gc,std_gc,abs_gc,liminf_gc,limsup_gc,cve_gc)
colnames(salida_gc)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_gc

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_noreg<-c(v_noreg_1,v_noreg_2,v_noreg_3,v_noreg_4,v_noreg_5,sum(elecciones$NoReg))
var_noreg<-c(var_noreg_1,var_noreg_2,var_noreg_3,var_noreg_4,var_noreg_5,var(elecciones$NoReg))
std_noreg<-c(std_noreg_1,std_noreg_2,std_noreg_3,std_noreg_4,std_noreg_5,sqrt(var(elecciones$NoReg)))
abs_noreg<-c(abs_noreg_1,abs_noreg_2,abs_noreg_3,abs_noreg_4,abs_noreg_5,sqrt(var(elecciones$NoReg))*qnorm(1-.05/2))
liminf_noreg<-c(liminf_noreg_1,liminf_noreg_2,liminf_noreg_3,liminf_noreg_4,liminf_noreg_5,0)
limsup_noreg<-c(limsup_noreg_1,limsup_noreg_2,limsup_noreg_3,limsup_noreg_4,limsup_noreg_5,0)
cve_noreg<-c(cve_noreg_1,cve_noreg_2,cve_noreg_3,cve_noreg_4,cve_noreg_5,0)

salida_noreg<-cbind(output_1,est_noreg,var_noreg,std_noreg,abs_noreg,liminf_noreg,limsup_noreg,cve_noreg)
colnames(salida_noreg)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_noreg

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_nulos<-c(v_nulos_1,v_nulos_2,v_nulos_3,v_nulos_4,v_nulos_5,sum(elecciones$Nulos))
var_nulos<-c(var_nulos_1,var_nulos_2,var_nulos_3,var_nulos_4,var_nulos_5,var(elecciones$Nulos))
std_nulos<-c(std_nulos_1,std_nulos_2,std_nulos_3,std_nulos_4,std_nulos_5,sqrt(var(elecciones$Nulos)))
abs_nulos<-c(abs_nulos_1,abs_nulos_2,abs_nulos_3,abs_nulos_4,abs_nulos_5,sqrt(var(elecciones$Nulos))*qnorm(1-.05/2))
liminf_nulos<-c(liminf_nulos_1,liminf_nulos_2,liminf_nulos_3,liminf_nulos_4,liminf_nulos_5,0)
limsup_nulos<-c(limsup_nulos_1,limsup_nulos_2,limsup_nulos_3,limsup_nulos_4,limsup_nulos_5,0)
cve_nulos<-c(cve_nulos_1,cve_nulos_2,cve_nulos_3,cve_nulos_4,cve_nulos_5,0)

salida_nulos<-cbind(output_1,est_nulos,var_nulos,std_nulos,abs_nulos,liminf_nulos,limsup_nulos,cve_nulos)
colnames(salida_nulos)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_nulos
```


Ahora el caso en el que usamos sampleo ponderado:

```{r}

## Numero de secciones por muestra
n1 <- 6500
n2 <- 500
n3 <- 250
n4 <- 100
n5 <- 50

## El N poblacional es

N<-nrow(elecciones)

#Extraer muestra n bajo muestreo aleatorio simple

Pk_1<- Pk.PropNorm.U(n1, elecciones$`LISTA NOMINAL`)
Pk_2<- Pk.PropNorm.U(n2, elecciones$`LISTA NOMINAL`)
Pk_3<- Pk.PropNorm.U(n3, elecciones$`LISTA NOMINAL`)
Pk_4<- Pk.PropNorm.U(n4, elecciones$`LISTA NOMINAL`)
Pk_5<- Pk.PropNorm.U(n5, elecciones$`LISTA NOMINAL`)

# Ahora necesitamos las probabilidades de inclusion de segundo orden, esto seria con el comando

muestra_1<- UPbrewer(Pk_1)
muestra_2<- UPbrewer(Pk_2)
muestra_3<- UPbrewer(Pk_3)
muestra_4<- UPbrewer(Pk_4)
muestra_5<- UPbrewer(Pk_5)

```

```{r}
Pk.m_1          <- Pk_1[muestra_1==1]
Pk.m_2          <- Pk_2[muestra_2==1]
Pk.m_3          <- Pk_3[muestra_3==1]
Pk.m_4          <- Pk_4[muestra_4==1]
Pk.m_5          <- Pk_5[muestra_5==1]

```

```{r}

mat_pk_1          <- Pkl.Hajek.s(Pk.m_1)
mat_pk_2          <- Pkl.Hajek.s(Pk.m_2)
mat_pk_3          <- Pkl.Hajek.s(Pk.m_3)
mat_pk_4          <- Pkl.Hajek.s(Pk.m_4)
mat_pk_5          <- Pkl.Hajek.s(Pk.m_5)

epn_1<-elecciones$EPN[muestra_1==1]
amlo_1<-elecciones$AMLO[muestra_1==1]
jvm_1<-elecciones$JVM[muestra_1==1]
gc_1<-elecciones$GC[muestra_1==1]
noreg_1<-elecciones$NoReg[muestra_1==1]
nulos_1<-elecciones$Nulos[muestra_1==1]

epn_2<-elecciones$EPN[muestra_2==1]
amlo_2<-elecciones$AMLO[muestra_2==1]
jvm_2<-elecciones$JVM[muestra_2==1]
gc_2<-elecciones$GC[muestra_2==1]
noreg_2<-elecciones$NoReg[muestra_2==1]
nulos_2<-elecciones$Nulos[muestra_2==1]

epn_3<-elecciones$EPN[muestra_3==1]
amlo_3<-elecciones$AMLO[muestra_3==1]
jvm_3<-elecciones$JVM[muestra_3==1]
gc_3<-elecciones$GC[muestra_3==1]
noreg_3<-elecciones$NoReg[muestra_3==1]
nulos_3<-elecciones$Nulos[muestra_3==1]

epn_4<-elecciones$EPN[muestra_4==1]
amlo_4<-elecciones$AMLO[muestra_4==1]
jvm_4<-elecciones$JVM[muestra_4==1]
gc_4<-elecciones$GC[muestra_4==1]
noreg_4<-elecciones$NoReg[muestra_4==1]
nulos_4<-elecciones$Nulos[muestra_4==1]

epn_5<-elecciones$EPN[muestra_5==1]
amlo_5<-elecciones$AMLO[muestra_5==1]
jvm_5<-elecciones$JVM[muestra_5==1]
gc_5<-elecciones$GC[muestra_5==1]
noreg_5<-elecciones$NoReg[muestra_5==1]
nulos_5<-elecciones$Nulos[muestra_5==1]


v_epn_1<-Est.Total.NHT(epn_1, pk_1)
v_amlo_1<-Est.Total.NHT(amlo_1, pk_1)
v_jvm_1<-Est.Total.NHT(jvm_1, pk_1)
v_gc_1<-Est.Total.NHT(gc_1, pk_1)
v_noreg_1<-Est.Total.NHT(noreg_1, pk_1)
v_nulos_1<-Est.Total.NHT(nulos_1, pk_1)

v_epn_2<-Est.Total.NHT(epn_2, pk_2)
v_amlo_2<-Est.Total.NHT(amlo_2, pk_2)
v_jvm_2<-Est.Total.NHT(jvm_2, pk_2)
v_gc_2<-Est.Total.NHT(gc_2, pk_2)
v_noreg_2<-Est.Total.NHT(noreg_2, pk_2)
v_nulos_2<-Est.Total.NHT(nulos_2, pk_2)

v_epn_3<-Est.Total.NHT(epn_3, pk_3)
v_amlo_3<-Est.Total.NHT(amlo_3, pk_3)
v_jvm_3<-Est.Total.NHT(jvm_3, pk_3)
v_gc_3<-Est.Total.NHT(gc_3, pk_3)
v_noreg_3<-Est.Total.NHT(noreg_3, pk_3)
v_nulos_3<-Est.Total.NHT(nulos_3, pk_3)

v_epn_4<-Est.Total.NHT(epn_4, pk_4)
v_amlo_4<-Est.Total.NHT(amlo_4, pk_4)
v_jvm_4<-Est.Total.NHT(jvm_4, pk_4)
v_gc_4<-Est.Total.NHT(gc_4, pk_4)
v_noreg_4<-Est.Total.NHT(noreg_4, pk_4)
v_nulos_4<-Est.Total.NHT(nulos_4, pk_4)

v_epn_5<-Est.Total.NHT(epn_5, pk_5)
v_amlo_5<-Est.Total.NHT(amlo_5, pk_5)
v_jvm_5<-Est.Total.NHT(jvm_5, pk_5)
v_gc_5<-Est.Total.NHT(gc_5, pk_5)
v_noreg_5<-Est.Total.NHT(noreg_5, pk_5)
v_nulos_5<-Est.Total.NHT(nulos_5, pk_5)





var_epn_1<-VE.SYG.Total.NHT(epn_1, Pk.m_1, mat_pk_1)
var_amlo_1<-VE.SYG.Total.NHT(amlo_1, Pk.m_1, mat_pk_1)
var_jvm_1<-VE.SYG.Total.NHT(jvm_1, Pk.m_1, mat_pk_1)
var_gc_1<-VE.SYG.Total.NHT(gc_1, Pk.m_1, mat_pk_1)
var_noreg_1<-VE.SYG.Total.NHT(noreg_1, Pk.m_1, mat_pk_1)
var_nulos_1<-VE.SYG.Total.NHT(nulos_1, Pk.m_1, mat_pk_1)


var_epn_2<-VE.SYG.Total.NHT(epn_2, Pk.m_2, mat_pk_2)
var_amlo_2<-VE.SYG.Total.NHT(amlo_2, Pk.m_2, mat_pk_2)
var_jvm_2<-VE.SYG.Total.NHT(jvm_2, Pk.m_2, mat_pk_2)
var_gc_2<-VE.SYG.Total.NHT(gc_2, Pk.m_2, mat_pk_2)
var_noreg_2<-VE.SYG.Total.NHT(noreg_2, Pk.m_2, mat_pk_2)
var_nulos_2<-VE.SYG.Total.NHT(nulos_2, Pk.m_2, mat_pk_2)


var_epn_3<-VE.SYG.Total.NHT(epn_3, Pk.m_3, mat_pk_3)
var_amlo_3<-VE.SYG.Total.NHT(amlo_3, Pk.m_3, mat_pk_3)
var_jvm_3<-VE.SYG.Total.NHT(jvm_3, Pk.m_3, mat_pk_3)
var_gc_3<-VE.SYG.Total.NHT(gc_3, Pk.m_3, mat_pk_3)
var_noreg_3<-VE.SYG.Total.NHT(noreg_3, Pk.m_3, mat_pk_3)
var_nulos_3<-VE.SYG.Total.NHT(nulos_3, Pk.m_3, mat_pk_3)


var_epn_4<-VE.SYG.Total.NHT(epn_4, Pk.m_4, mat_pk_4)
var_amlo_4<-VE.SYG.Total.NHT(amlo_4, Pk.m_4, mat_pk_4)
var_jvm_4<-VE.SYG.Total.NHT(jvm_4, Pk.m_4, mat_pk_4)
var_gc_4<-VE.SYG.Total.NHT(gc_4, Pk.m_4, mat_pk_4)
var_noreg_4<-VE.SYG.Total.NHT(noreg_4, Pk.m_4, mat_pk_4)
var_nulos_4<-VE.SYG.Total.NHT(nulos_4, Pk.m_4, mat_pk_4)


var_epn_5<-VE.SYG.Total.NHT(epn_5, Pk.m_5, mat_pk_5)
var_amlo_5<-VE.SYG.Total.NHT(amlo_5, Pk.m_5, mat_pk_5)
var_jvm_5<-VE.SYG.Total.NHT(jvm_5, Pk.m_5, mat_pk_5)
var_gc_5<-VE.SYG.Total.NHT(gc_5, Pk.m_5, mat_pk_5)
var_noreg_5<-VE.SYG.Total.NHT(noreg_5, Pk.m_5, mat_pk_5)
var_nulos_5<-VE.SYG.Total.NHT(nulos_5, Pk.m_5, mat_pk_5)


std_epn_1   <- sqrt(var_epn_1)
std_amlo_1 <- sqrt(var_amlo_1)
std_jvm_1 <- sqrt(var_jvm_1)
std_gc_1 <- sqrt(var_gc_1)
std_noreg_1 <- sqrt(var_noreg_1)
std_nulos_1 <- sqrt(var_nulos_1)


std_epn_2   <- sqrt(var_epn_2)
std_amlo_2 <- sqrt(var_amlo_2)
std_jvm_2 <- sqrt(var_jvm_2)
std_gc_2 <- sqrt(var_gc_2)
std_noreg_2 <- sqrt(var_noreg_2)
std_nulos_2 <- sqrt(var_nulos_2)

std_epn_3   <- sqrt(var_epn_3)
std_amlo_3 <- sqrt(var_amlo_3)
std_jvm_3 <- sqrt(var_jvm_3)
std_gc_3 <- sqrt(var_gc_3)
std_noreg_3 <- sqrt(var_noreg_3)
std_nulos_3 <- sqrt(var_nulos_3)

std_epn_4   <- sqrt(var_epn_4)
std_amlo_4 <- sqrt(var_amlo_4)
std_jvm_4 <- sqrt(var_jvm_4)
std_gc_4 <- sqrt(var_gc_4)
std_noreg_4 <- sqrt(var_noreg_4)
std_nulos_4 <- sqrt(var_nulos_4)

std_epn_5   <- sqrt(var_epn_5)
std_amlo_5 <- sqrt(var_amlo_5)
std_jvm_5 <- sqrt(var_jvm_5)
std_gc_5 <- sqrt(var_gc_5)
std_noreg_5 <- sqrt(var_noreg_5)
std_nulos_5 <- sqrt(var_nulos_5)



# Y ahora calculemos nuestro error absoluto o precision al 95% de confianza
alpha              <- 0.05
abs_epn_1    <- std_epn_1*qnorm(1-alpha/2)
abs_amlo_1    <- std_amlo_1*qnorm(1-alpha/2)
abs_jvm_1    <- std_jvm_1*qnorm(1-alpha/2)
abs_gc_1    <- std_gc_1*qnorm(1-alpha/2)
abs_noreg_1    <- std_noreg_1*qnorm(1-alpha/2)
abs_nulos_1    <- std_nulos_1*qnorm(1-alpha/2)

abs_epn_2    <- std_epn_2*qnorm(1-alpha/2)
abs_amlo_2    <- std_amlo_2*qnorm(1-alpha/2)
abs_jvm_2    <- std_jvm_2*qnorm(1-alpha/2)
abs_gc_2    <- std_gc_2*qnorm(1-alpha/2)
abs_noreg_2    <- std_noreg_2*qnorm(1-alpha/2)
abs_nulos_2    <- std_nulos_2*qnorm(1-alpha/2)


abs_epn_3    <- std_epn_3*qnorm(1-alpha/2)
abs_amlo_3    <- std_amlo_3*qnorm(1-alpha/2)
abs_jvm_3    <- std_jvm_3*qnorm(1-alpha/2)
abs_gc_3    <- std_gc_3*qnorm(1-alpha/2)
abs_noreg_3    <- std_noreg_3*qnorm(1-alpha/2)
abs_nulos_3    <- std_nulos_3*qnorm(1-alpha/2)

abs_epn_4    <- std_epn_4*qnorm(1-alpha/2)
abs_amlo_4    <- std_amlo_4*qnorm(1-alpha/2)
abs_jvm_4    <- std_jvm_4*qnorm(1-alpha/2)
abs_gc_4    <- std_gc_4*qnorm(1-alpha/2)
abs_noreg_4    <- std_noreg_4*qnorm(1-alpha/2)
abs_nulos_4    <- std_nulos_4*qnorm(1-alpha/2)


abs_epn_5    <- std_epn_5*qnorm(1-alpha/2)
abs_amlo_5    <- std_amlo_5*qnorm(1-alpha/2)
abs_jvm_5    <- std_jvm_5*qnorm(1-alpha/2)
abs_gc_5    <- std_gc_5*qnorm(1-alpha/2)
abs_noreg_5    <- std_noreg_5*qnorm(1-alpha/2)
abs_nulos_5    <- std_nulos_5*qnorm(1-alpha/2)

# Entonces nuestros 4 intervalos de confianza a un nivel de 95% son:
liminf_epn_1  <- v_epn_1 - abs_epn_1
liminf_amlo_1  <- v_amlo_1 - abs_amlo_1
liminf_jvm_1  <- v_jvm_1 - abs_jvm_1
liminf_gc_1  <- v_gc_1 - abs_gc_1
liminf_noreg_1  <- v_noreg_1 - abs_noreg_1
liminf_nulos_1  <- v_nulos_1 - abs_nulos_1

limsup_epn_1  <- v_epn_1 + abs_epn_1
limsup_amlo_1  <- v_amlo_1 + abs_amlo_1
limsup_jvm_1  <- v_jvm_1 + abs_jvm_1
limsup_gc_1  <- v_gc_1 + abs_gc_1
limsup_noreg_1  <- v_noreg_1 + abs_noreg_1
limsup_nulos_1  <- v_nulos_1 + abs_nulos_1


liminf_epn_2  <- v_epn_2 - abs_epn_2
liminf_amlo_2  <- v_amlo_2 - abs_amlo_2
liminf_jvm_2  <- v_jvm_2 - abs_jvm_2
liminf_gc_2  <- v_gc_2 - abs_gc_2
liminf_noreg_2  <- v_noreg_2 - abs_noreg_2
liminf_nulos_2  <- v_nulos_2 - abs_nulos_2

limsup_epn_2  <- v_epn_2 + abs_epn_2
limsup_amlo_2  <- v_amlo_2 + abs_amlo_2
limsup_jvm_2  <- v_jvm_2 + abs_jvm_2
limsup_gc_2  <- v_gc_2 + abs_gc_2
limsup_noreg_2  <- v_noreg_2 + abs_noreg_2
limsup_nulos_2  <- v_nulos_2 + abs_nulos_2



liminf_epn_3  <- v_epn_3 - abs_epn_3
liminf_amlo_3  <- v_amlo_3 - abs_amlo_3
liminf_jvm_3  <- v_jvm_3 - abs_jvm_3
liminf_gc_3  <- v_gc_3 - abs_gc_3
liminf_noreg_3  <- v_noreg_3 - abs_noreg_3
liminf_nulos_3  <- v_nulos_3 - abs_nulos_3

limsup_epn_3  <- v_epn_3 + abs_epn_3
limsup_amlo_3  <- v_amlo_3 + abs_amlo_3
limsup_jvm_3  <- v_jvm_3 + abs_jvm_3
limsup_gc_3  <- v_gc_3 + abs_gc_3
limsup_noreg_3  <- v_noreg_3 + abs_noreg_3
limsup_nulos_3  <- v_nulos_3 + abs_nulos_3

liminf_epn_4  <- v_epn_4 - abs_epn_4
liminf_amlo_4  <- v_amlo_4 - abs_amlo_4
liminf_jvm_4  <- v_jvm_4 - abs_jvm_4
liminf_gc_4  <- v_gc_4 - abs_gc_4
liminf_noreg_4  <- v_noreg_4 - abs_noreg_4
liminf_nulos_4  <- v_nulos_4 - abs_nulos_4

limsup_epn_4  <- v_epn_4 + abs_epn_4
limsup_amlo_4  <- v_amlo_4 + abs_amlo_4
limsup_jvm_4  <- v_jvm_4 + abs_jvm_4
limsup_gc_4  <- v_gc_4 + abs_gc_4
limsup_noreg_4  <- v_noreg_4 + abs_noreg_4
limsup_nulos_4  <- v_nulos_4 + abs_nulos_4

liminf_epn_5  <- v_epn_5 - abs_epn_5
liminf_amlo_5  <- v_amlo_5 - abs_amlo_5
liminf_jvm_5  <- v_jvm_5 - abs_jvm_5
liminf_gc_5  <- v_gc_5 - abs_gc_5
liminf_noreg_5  <- v_noreg_5 - abs_noreg_5
liminf_nulos_5  <- v_nulos_5 - abs_nulos_5

limsup_epn_5  <- v_epn_5 + abs_epn_5
limsup_amlo_5  <- v_amlo_5 + abs_amlo_5
limsup_jvm_5  <- v_jvm_5 + abs_jvm_5
limsup_gc_5  <- v_gc_5 + abs_gc_5
limsup_noreg_5  <- v_noreg_5 + abs_noreg_5
limsup_nulos_5  <- v_nulos_5 + abs_nulos_5

# Ahora calculemos el coeficiente de variaci?n estimado de cada una de las 4 estimaciones...
cve_epn_1      <- std_epn_1/v_epn_1
cve_amlo_1      <- std_amlo_1/v_amlo_1
cve_jvm_1      <- std_jvm_1/v_jvm_1
cve_gc_1      <- std_gc_1/v_gc_1
cve_noreg_1      <- std_noreg_1/v_noreg_1
cve_nulos_1      <- std_nulos_1/v_nulos_1

cve_epn_2      <- std_epn_2/v_epn_2
cve_amlo_2      <- std_amlo_2/v_amlo_2
cve_jvm_2      <- std_jvm_2/v_jvm_2
cve_gc_2      <- std_gc_2/v_gc_2
cve_noreg_2      <- std_noreg_2/v_noreg_2
cve_nulos_2      <- std_nulos_2/v_nulos_2

cve_epn_3      <- std_epn_3/v_epn_3
cve_amlo_3      <- std_amlo_3/v_amlo_3
cve_jvm_3      <- std_jvm_3/v_jvm_3
cve_gc_3      <- std_gc_3/v_gc_3
cve_noreg_3      <- std_noreg_3/v_noreg_3
cve_nulos_3      <- std_nulos_3/v_nulos_3

cve_epn_4      <- std_epn_4/v_epn_4
cve_amlo_4      <- std_amlo_4/v_amlo_4
cve_jvm_4      <- std_jvm_4/v_jvm_4
cve_gc_4      <- std_gc_4/v_gc_4
cve_noreg_4      <- std_noreg_4/v_noreg_4
cve_nulos_4      <- std_nulos_4/v_nulos_4

cve_epn_5      <- std_epn_5/v_epn_5
cve_amlo_5      <- std_amlo_5/v_amlo_5
cve_jvm_5      <- std_jvm_5/v_jvm_5
cve_gc_5      <- std_gc_5/v_gc_5
cve_noreg_5      <- std_noreg_5/v_noreg_5
cve_nulos_5      <- std_nulos_5/v_nulos_5

```


```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_epn<-c(v_epn_1,v_epn_2,v_epn_3,v_epn_4,v_epn_5,sum(elecciones$EPN))
var_epn<-c(var_epn_1,var_epn_2,var_epn_3,var_epn_4,var_epn_5,var(elecciones$EPN))
std_epn<-c(std_epn_1,std_epn_2,std_epn_3,std_epn_4,std_epn_5,sqrt(var(elecciones$EPN)))
abs_epn<-c(abs_epn_1,abs_epn_2,abs_epn_3,abs_epn_4,abs_epn_5,sqrt(var(elecciones$EPN))*qnorm(1-.05/2))
liminf_epn<-c(liminf_epn_1,liminf_epn_2,liminf_epn_3,liminf_epn_4,liminf_epn_5,0)
limsup_epn<-c(limsup_epn_1,limsup_epn_2,limsup_epn_3,limsup_epn_4,limsup_epn_5,0)
cve_epn<-c(cve_epn_1,cve_epn_2,cve_epn_3,cve_epn_4,cve_epn_5,0)

salida_epn_pk<-cbind(output_1,est_epn,var_epn,std_epn,abs_epn,liminf_epn,limsup_epn,cve_epn)
colnames(salida_epn_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_epn_pk

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_amlo<-c(v_amlo_1,v_amlo_2,v_amlo_3,v_amlo_4,v_amlo_5,sum(elecciones$AMLO))
var_amlo<-c(var_amlo_1,var_amlo_2,var_amlo_3,var_amlo_4,var_amlo_5,var(elecciones$AMLO))
std_amlo<-c(std_amlo_1,std_amlo_2,std_amlo_3,std_amlo_4,std_amlo_5,sqrt(var(elecciones$AMLO)))
abs_amlo<-c(abs_amlo_1,abs_amlo_2,abs_amlo_3,abs_amlo_4,abs_amlo_5,sqrt(var(elecciones$AMLO))*qnorm(1-.05/2))
liminf_amlo<-c(liminf_amlo_1,liminf_amlo_2,liminf_amlo_3,liminf_amlo_4,liminf_amlo_5,0)
limsup_amlo<-c(limsup_amlo_1,limsup_amlo_2,limsup_amlo_3,limsup_amlo_4,limsup_amlo_5,0)
cve_amlo<-c(cve_amlo_1,cve_amlo_2,cve_amlo_3,cve_amlo_4,cve_amlo_5,0)

salida_amlo_pk<-cbind(output_1,est_amlo,var_amlo,std_amlo,abs_amlo,liminf_amlo,limsup_amlo,cve_amlo)
colnames(salida_amlo_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_amlo_pk

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_jvm<-c(v_jvm_1,v_jvm_2,v_jvm_3,v_jvm_4,v_jvm_5,sum(elecciones$JVM))
var_jvm<-c(var_jvm_1,var_jvm_2,var_jvm_3,var_jvm_4,var_jvm_5,var(elecciones$JVM))
std_jvm<-c(std_jvm_1,std_jvm_2,std_jvm_3,std_jvm_4,std_jvm_5,sqrt(var(elecciones$JVM)))
abs_jvm<-c(abs_jvm_1,abs_jvm_2,abs_jvm_3,abs_jvm_4,abs_jvm_5,sqrt(var(elecciones$JVM))*qnorm(1-.05/2))
liminf_jvm<-c(liminf_jvm_1,liminf_jvm_2,liminf_jvm_3,liminf_jvm_4,liminf_jvm_5,0)
limsup_jvm<-c(limsup_jvm_1,limsup_jvm_2,limsup_jvm_3,limsup_jvm_4,limsup_jvm_5,0)
cve_jvm<-c(cve_jvm_1,cve_jvm_2,cve_jvm_3,cve_jvm_4,cve_jvm_5,0)

salida_jvm_pk<-cbind(output_1,est_jvm,var_jvm,std_jvm,abs_jvm,liminf_jvm,limsup_jvm,cve_jvm)
colnames(salida_jvm_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_jvm_pk

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_gc<-c(v_gc_1,v_gc_2,v_gc_3,v_gc_4,v_gc_5,sum(elecciones$GC))
var_gc<-c(var_gc_1,var_gc_2,var_gc_3,var_gc_4,var_gc_5,var(elecciones$GC))
std_gc<-c(std_gc_1,std_gc_2,std_gc_3,std_gc_4,std_gc_5,sqrt(var(elecciones$GC)))
abs_gc<-c(abs_gc_1,abs_gc_2,abs_gc_3,abs_gc_4,abs_gc_5,sqrt(var(elecciones$GC))*qnorm(1-.05/2))
liminf_gc<-c(liminf_gc_1,liminf_gc_2,liminf_gc_3,liminf_gc_4,liminf_gc_5,0)
limsup_gc<-c(limsup_gc_1,limsup_gc_2,limsup_gc_3,limsup_gc_4,limsup_gc_5,0)
cve_gc<-c(cve_gc_1,cve_gc_2,cve_gc_3,cve_gc_4,cve_gc_5,0)

salida_gc_pk<-cbind(output_1,est_gc,var_gc,std_gc,abs_gc,liminf_gc,limsup_gc,cve_gc)
colnames(salida_gc_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_gc_pk

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_noreg<-c(v_noreg_1,v_noreg_2,v_noreg_3,v_noreg_4,v_noreg_5,sum(elecciones$NoReg))
var_noreg<-c(var_noreg_1,var_noreg_2,var_noreg_3,var_noreg_4,var_noreg_5,var(elecciones$NoReg))
std_noreg<-c(std_noreg_1,std_noreg_2,std_noreg_3,std_noreg_4,std_noreg_5,sqrt(var(elecciones$NoReg)))
abs_noreg<-c(abs_noreg_1,abs_noreg_2,abs_noreg_3,abs_noreg_4,abs_noreg_5,sqrt(var(elecciones$NoReg))*qnorm(1-.05/2))
liminf_noreg<-c(liminf_noreg_1,liminf_noreg_2,liminf_noreg_3,liminf_noreg_4,liminf_noreg_5,0)
limsup_noreg<-c(limsup_noreg_1,limsup_noreg_2,limsup_noreg_3,limsup_noreg_4,limsup_noreg_5,0)
cve_noreg<-c(cve_noreg_1,cve_noreg_2,cve_noreg_3,cve_noreg_4,cve_noreg_5,0)

salida_noreg_pk<-cbind(output_1,est_noreg,var_noreg,std_noreg,abs_noreg,liminf_noreg,limsup_noreg,cve_noreg)
colnames(salida_noreg_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_noreg_pk

```

```{r}
output_1<-c(n1,n2,n3,n4,n5,nrow(elecciones)) %>% as.vector()
est_nulos<-c(v_nulos_1,v_nulos_2,v_nulos_3,v_nulos_4,v_nulos_5,sum(elecciones$Nulos))
var_nulos<-c(var_nulos_1,var_nulos_2,var_nulos_3,var_nulos_4,var_nulos_5,var(elecciones$Nulos))
std_nulos<-c(std_nulos_1,std_nulos_2,std_nulos_3,std_nulos_4,std_nulos_5,sqrt(var(elecciones$Nulos)))
abs_nulos<-c(abs_nulos_1,abs_nulos_2,abs_nulos_3,abs_nulos_4,abs_nulos_5,sqrt(var(elecciones$Nulos))*qnorm(1-.05/2))
liminf_nulos<-c(liminf_nulos_1,liminf_nulos_2,liminf_nulos_3,liminf_nulos_4,liminf_nulos_5,0)
limsup_nulos<-c(limsup_nulos_1,limsup_nulos_2,limsup_nulos_3,limsup_nulos_4,limsup_nulos_5,0)
cve_nulos<-c(cve_nulos_1,cve_nulos_2,cve_nulos_3,cve_nulos_4,cve_nulos_5,0)

salida_nulos_pk<-cbind(output_1,est_nulos,var_nulos,std_nulos,abs_nulos,liminf_nulos,limsup_nulos,cve_nulos)
colnames(salida_nulos_pk)<-c("Tamaño de muestra","Estimación de votos","Varianza","Error estándar","Abs", "Limite inf", "Límite sup", "Coeficiente de variación")
salida_nulos_pk
```







